os:
  - osx
sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
before_install:

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install -g yarn bower cordova ionic jasmine
  - yarn install
  - yarn run install:post
  - bower install
  - yarn run build:client
notifications:
  slack: missourpro:PR6GCxcqcAQ06gne1aVkS08n
