sudo: required
language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g yarn
  - yarn global add bower cordova ionic jasmine
  - yarn install
  - yarn run install:post
  - bower install
  - yarn run build:client
notifications:
  slack: missourpro:PR6GCxcqcAQ06gne1aVkS08n
