os: Visual Studio 2015
environment:
  matrix:
    - nodejs_version: "6.9.5"
init:
  - git config --global core.autocrlf input

branches:
  only:
    - master
cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn cordova ionic jasmine bower
  - yarn install
  - yarn run install:post
  - bower install
build_script:
  - yarn run build:client
test_script:
  - node --version
  - yarn run test
notifications:
  - provider: Slack
    auth_token:
      secure: gyOmEvdmMF5DZBwT7rwjuouSraSMAladoARizAyFwGuUBwO5zqFBYE/6Gse1icxJdPjzR68OwrE8Y9c7ckP8obeCSaYDS2Ed4sVLt6+SYCc=
    channel: '#video-app'
